Adding a node version for heroku
andela/ah-frontend-sparta pull request #21
Opened 2019-05-09 07:48 UTC by felixkiryowa

Test the heroku deployment.

2019-05-09 11:09 UTC, ezrogha requested changes
Well done with this fix @felixkiryowa,
Kindly work on all indentations, they should be two spaces

2019-05-09 11:09 UTC, ezrogha commented on src/components/InputBox/index.js
> +		</div>
@felixkiryowa please work on this indentation,
It should be two spaces

2019-05-10 12:40 UTC, adesege commented
@felixkiryowa Fix the merge conflict on this PR

2019-05-13 08:38 UTC, felixkiryowa commented
I have closed this PR because , Heroku was fixed and it is working

2019-05-13 08:39 UTC, closed without merging