#165909011 Getting articles from an endpoint to display on the landing page
andela/ah-frontend-sparta pull request #22
Opened 2019-05-09 12:58 UTC by felixkiryowa

#### What does this PR do?

-  Consuming Articles API on the landing page

#### Description of Task to be completed?
-  A user should be able to view sample articles when a landing page is loaded

#### How should this be manually tested?

- Fetch this branch `git fetch origin  ft-landing-page-getting-articles-165909011`
- Checkout to the branch `git checkout  ft-landing-page-getting-articles-165909011`
- Run `npm install`
- Run `npm run start:dev`

#### What are the relevant pivotal tracker stories?
[ #165909011 ](hhttps://www.pivotaltracker.com/story/show/165909011)

2019-05-13 08:03 UTC, ezrogha requested changes
Hey @felixkiryowa, 
kindly work on this feedback

2019-05-13 08:03 UTC, ezrogha commented on src/components/Articles/DisplaySampleArticles.js
> +    const article = props.sampleArticle;
Hey @felixkiryowa,
instead of adding an extra lines of code It would be better to destructure the prop as a function argument i.e 
```
const functionName = ({ sampleAtricles }) => 
```
so as to get rid of declaration and return statemen

2019-05-13 08:03 UTC, ezrogha commented on src/components/Articles/ArticleContainer.js
> +    return (
Hey @felixkiryowa,
This line(6) is not neccesary and please destructure your code.

2019-05-13 08:03 UTC, ezrogha commented on src/components/Articles/DisplayTrendingArticles.js
> +    return (
Please apply the feedback above here as well

2019-05-13 08:03 UTC, ezrogha commented on src/components/Articles/TrendingArticles.js
> +        // Since we are only removing one element
Please remove this coment

2019-05-13 08:03 UTC, ezrogha commented on src/components/Articles/TrendingArticles.js
> +    // Make a copy of the array
please remove this comment

2019-05-13 08:03 UTC, ezrogha commented on src/components/Articles/TrendingArticles.js
> +    const { articles } = props;
Please destructure from the function argument, you don't have to create a new variable

2019-05-13 08:03 UTC, ezrogha commented on src/components/Articles/index.js
> +    const { articles } = props;
Please destructure in function arguments

2019-05-13 08:03 UTC, ezrogha commented on src/components/NavBar/index.js
>    return (
This line is not necessary

2019-05-13 08:03 UTC, ezrogha commented on src/pages/Landing/Landing.scss
>      width: 720px;
please use function to convert to rem

2019-05-13 08:03 UTC, ezrogha commented on src/pages/Landing/Landing.scss
> +  padding-left: 10px;
please convert to rem

2019-05-13 08:03 UTC, ezrogha commented on src/pages/Landing/index.js
> +}
Please use double quotes when writing tag attributes or props for components

2019-05-13 08:03 UTC, ezrogha commented on src/tests/Signin.test..js
> +    );
please format this document

2019-05-13 08:03 UTC, ezrogha commented on src/tests/actions/ArticlesActions.test.js
> +
please format this document

2019-05-13 11:25 UTC, felixkiryowa commented on src/tests/Signin.test..js
> +    );
I have worked on this feedback

2019-05-13 11:33 UTC, adesege requested changes

2019-05-13 11:33 UTC, adesege commented on src/actions/articlesActions.js
> +  axios.get('https://ah-backend.herokuapp.com/api/articles/')
Do not hardcode the host name in your code. You can take advantage of axios's baseUrl. Also, you are meant to import axios from the helpers folder.

2019-05-13 11:33 UTC, adesege commented on src/components/Articles/ArticleContainer.jsx
> +  articles: PropTypes.arrayOf(PropTypes.array.isRequired),
Is the prop an array of array or array of object?

2019-05-13 11:33 UTC, adesege commented on src/components/Articles/DisplaySampleArticles.jsx
> +  sampleArticle: PropTypes.arrayOf(PropTypes.array.isRequired),
Is the prop an array of array or array of object?

2019-05-13 11:33 UTC, adesege commented on src/components/Articles/DisplayTrendingArticles.jsx
> +  trendingArticles: PropTypes.arrayOf(PropTypes.array.isRequired),
Is the prop an array of array or array of object?

2019-05-13 11:33 UTC, adesege commented on src/components/Articles/TrendingArticles.jsx
> +        randomArray.map((article) => {
Move this to a method instead

2019-05-13 11:33 UTC, adesege commented on src/components/Articles/TrendingArticles.jsx
> +  articles: PropTypes.arrayOf(PropTypes.array.isRequired),
Is the prop an array of array or array of object?

2019-05-13 11:33 UTC, adesege commented on src/components/Articles/index.jsx
> +SampleArticles.propTypes = {
Remove this line

2019-05-13 11:33 UTC, adesege commented on src/components/Articles/index.jsx
> +  articles: PropTypes.arrayOf(PropTypes.array.isRequired),
Is the prop an array of array or array of object?

2019-05-13 11:33 UTC, adesege commented on src/pages/Landing/index.jsx
> +  articles: PropTypes.arrayOf(PropTypes.array.isRequired),
Is the prop an array of array or array of object?

2019-05-13 11:33 UTC, adesege commented on src/tests/App.test.js
>    it('should render without crashing', () => {
Also add a test to display an article on the landing page

2019-05-13 11:33 UTC, adesege commented on src/tests/actions/ArticlesActions.test.js
> +describe('Test', () => {
Give the test suite and case a more descriptive name

2019-05-13 11:33 UTC, adesege commented on src/tests/components/__snapshots__/TrendingArticles.test.js.snap
> +exports[`Articles Component Should render without crashing 1`] = `ReactWrapper {}`;
This snapshot doesn't render the necessary articles

2019-05-13 11:33 UTC, adesege commented on src/tests/components/__snapshots__/sampleArticles.test.js.snap
> +exports[`Sample Articles Component Should render without crashing 1`] = `ReactWrapper {}`;
This snapshot doesn't render the necessary articles

2019-05-13 12:01 UTC, dannylwe commented on src/components/Articles/DisplayTrendingArticles.jsx
> +          {' '}
Hi, for the next PR, kindly put strings and stuff in a reusable component

2019-05-13 14:06 UTC, ezrogha approved these changes
Well done with the feedback @felixkiryowa,
LGTM

2019-05-13 16:45 UTC, dannylwe approved these changes
Looks good, you've worked on the feedback given.

2019-05-13 17:35 UTC, adesege requested changes
Note that only React components should end with a .jsx extension while pure javascript files should end with .js

2019-05-13 17:35 UTC, adesege commented on src/actions/types.js
> +export default GET_ARTICLES;
You shouldn't use export default here because this file is going to export a lot of type constants

2019-05-13 17:35 UTC, adesege commented on src/components/Articles/DisplaySampleArticles.jsx
> +  sampleArticle: shape({}),
You shouldn't use the shape function here. It's meant for type checking

2019-05-13 17:35 UTC, adesege commented on src/components/Articles/DisplaySampleArticles.jsx
> +  sampleArticle: shape({ id: PropTypes.number }),
If you are going to use `propTypes.shape()`, then you need to define all the possible properties `sampleArticle` will take. If not, you can just use `propTypes.object().isRequired`

2019-05-13 17:35 UTC, adesege commented on src/helpers/randomArticles.js
> +const getRandomArticles = (count, articles) => {
Since you are consuming the api now, do you need a function to display random article?

2019-05-13 17:35 UTC, adesege commented on src/pages/Landing/Landing.scss
> +@media (max-width: rem(576)) {
Device dimensions should be fixed. You can use pixels here instead.

2019-05-13 17:35 UTC, adesege commented on src/pages/Landing/tests/__snapshots__/Landing.test.js.snap
> +        No Posts where Found !!!!
Let your test have at least one post in each category

2019-05-13 17:35 UTC, adesege commented on src/pages/Landing/tests/Landing.test.js
> +  it('should render without crashing', () => {
Add a test to call `componentDidMount` in the component's test

2019-05-13 17:35 UTC, adesege commented on src/tests/actions/ArticlesActions.test.jsx
> +import moxios from 'moxios';
The file name shouldn't be in .jsx because the test's file is not a component but a pure javascript file

2019-05-14 08:45 UTC, adesege submitted a review, later dismissed
I see you haven't worked on most of the feedback I gave. Also, note that I will be the one to resolve a conversation once I'm satisfied that the feedback has been implemented

2019-05-14 08:45 UTC, adesege commented on dist/config.js
> +const baseURL = 'https://ah-backend.herokuapp.com/api/';
Remove this file

2019-05-14 08:45 UTC, adesege commented on package.json
> +    "react-css-themr": "^2.1.2",
What's the use for this package?

2019-05-14 08:45 UTC, adesege commented on src/actions/articlesActions.js
> +import axios from 'axios';
Import axios from the helpers file

2019-05-14 08:45 UTC, adesege commented on src/actions/types.js
> +export default GET_ARTICLES;
You haven't worked on this feedback

2019-05-14 08:45 UTC, adesege commented on src/components/Articles/DisplaySampleArticles.jsx
> +  sampleArticle: shape({}),
You haven't worked on this feedback

2019-05-14 08:45 UTC, adesege commented on src/components/Articles/DisplaySampleArticles.jsx
> +  sampleArticle: shape({ id: PropTypes.number }),
You haven't worked on this feedback

2019-05-14 08:45 UTC, adesege commented on src/helpers/randomArticles.js
> +const getRandomArticles = (count, articles) => {
☝️

2019-05-15 11:09 UTC, ezrogha commented
Hey @felixkiryowa, 
I can't seem to see any posts on the landing page why is that?
<img width="1439" alt="Screenshot 2019-05-15 at 14 08 04" src="https://user-images.githubusercontent.com/35653907/57771283-f54f9800-771a-11e9-8a1b-5705176e66fd.png">

Please also provide screenshots and make sure your PT story ID is a link

2019-05-15 11:26 UTC, dorothyas approved these changes

2019-05-15 11:30 UTC, ezrogha approved these changes
LGTM

2019-05-15 12:16 UTC, hadijahkyampeire approved these changes
Good work

2019-05-15 12:17 UTC, merged