feat(create articles) Creating articles
andela/ah-frontend-sparta pull request #32
Opened 2019-05-16 12:38 UTC by felixkiryowa

#### What does this PR do?

- Creating Articles and Get Articles

#### Description of Task to be completed?
-  A user should be able to view articles and get articles when they have logged in.

#### How should this be manually tested?

- Fetch this branch `git fetch origin ft-create-articles-164798168`
- Checkout to the branch `git checkout  ft-create-articles-164798168`
- Run `npm install`
- Run `npm run start:dev`

#### What are the relevant pivotal tracker stories?
[ #164798168 ](https://www.pivotaltracker.com/story/show/164798168)
<img width="1440" alt="Screenshot 2019-05-16 at 15 35 26" src="https://user-images.githubusercontent.com/28748289/57854258-7e84ce80-77f0-11e9-9b4c-88dd3392a470.png">
<img width="1440" alt="Screenshot 2019-05-16 at 15 35 58" src="https://user-images.githubusercontent.com/28748289/57854260-7e84ce80-77f0-11e9-976a-d06ce5e5bf1f.png">
<img width="1440" alt="Screenshot 2019-05-16 at 15 36 25" src="https://user-images.githubusercontent.com/28748289/57854263-7f1d6500-77f0-11e9-86d8-9ce5d7b6fde3.png">
<img width="1440" alt="Screenshot 2019-05-16 at 15 36 43" src="https://user-images.githubusercontent.com/28748289/57854264-7f1d6500-77f0-11e9-93a4-c681c6185ff7.png">

2019-05-16 16:26 UTC, dannylwe requested changes

2019-05-16 16:26 UTC, dannylwe commented on .env
> +baseURL=https://ah-backend.herokuapp.com/api
@felixkiryowa do not push the .env file

2019-05-16 16:26 UTC, dannylwe commented on .eslintrc.js
> +		"no- param-reassign":"off",
@felixkiryowa do not touch the eslint file 👍

2019-05-16 16:26 UTC, dannylwe commented on src/components/Articles/article.scss
> +    border-radius: 2px;
@felixkiryowa convert px to rem

2019-05-16 16:26 UTC, dannylwe commented on src/components/SignupForm/index.jsx
> +    <p style={{ fontSize: '20px', paddingLeft: '65px' }}>
@felixkiryowa convert px to rem

2019-05-16 16:26 UTC, dannylwe commented on src/pages/Articles/articles.scss
> +}
convert px to rem

2019-05-17 11:34 UTC, dorothyas approved these changes

2019-05-17 11:34 UTC, dorothyas commented on src/helpers/axiosInstance.js
> +
please remove this commented out code

2019-05-17 11:34 UTC, dorothyas commented on src/pages/Articles/tests/__snapshots__/createArticlePage.test.jsx.snap
> +exports[`Articles Page Component Should render without crashing 1`] = `ReactWrapper {}`;
it appears the component of this test was not rendered.

2019-05-17 11:34 UTC, dorothyas commented on src/pages/Dashboard/tests/__snapshots__/Dashboard.test.jsx.snap
> +exports[`Dashboard Component should render without crashing 1`] = `ReactWrapper {}`;
this component as well was not rendered

2019-05-17 11:34 UTC, dorothyas commented on src/pages/singleArticle/tests/__snapshots__/singleArticle.test.jsx.snap
> +exports[`Single Article page should render without crashing 1`] = `ReactWrapper {}`;
look into this snapshot as well

2019-05-17 11:35 UTC, dannylwe approved these changes

2019-05-17 11:36 UTC, merged