#164798171 Pagination support for Articles
andela/ah-frontend-sparta pull request #34
Opened 2019-05-17 08:45 UTC by dorothyas

**what does this PR do?**
- this enables users to view a specified number of articles and go to the next page for more articles

**What are the relevant Pivotal Tracker stories?**

[#164798171](https://www.pivotaltracker.com/n/projects/2320796/stories/164798171)

2019-05-20 09:56 UTC, ezrogha requested changes
Hey @dorothyas,
Good work here,
kindly work on this feedback

2019-05-20 09:56 UTC, ezrogha commented on src/actions/profileActions.js
> +      // eslint-disable-next-line no-restricted-globals
Hey @dorothyas, 
Kindly get rid of this comment

2019-05-20 09:56 UTC, ezrogha commented on src/components/NavBarAccountSection/index.jsx
> +// eslint-disable-next-line react/prop-types
Please remove this comment

2019-05-20 09:56 UTC, ezrogha commented on src/pages/Dashboard/index.jsx
> +    const { articles, firstarticles, paginatearticles } = this.props;
Be consistent with the use of camelcase

2019-05-20 09:56 UTC, ezrogha commented on src/pages/Landing/index.jsx
> +/* eslint-disable react/destructuring-assignment */
Please remove these comments

2019-05-20 10:41 UTC, felixkiryowa submitted a review, later dismissed

2019-05-20 10:41 UTC, felixkiryowa commented on src/pages/Landing/index.jsx
> +            {paginatearticles.length === 0 ? <ArticleContainer articles={firstarticles} /> : <ArticleContainer articles={paginatearticles} />}
@dorothyas Formatting of this line is required

2019-05-21 15:34 UTC, ezrogha submitted a review, later dismissed
Great work with the feedback @dorothyas,
I realise the coverage has slightly dropped. 
please work on this

2019-05-22 08:28 UTC, hadijahkyampeire approved these changes
Well done but we might need a follow up PR for this after the backend fix

2019-05-22 08:30 UTC, merged