#164798172 Users should be able to like and or dislike articles
andela/ah-frontend-sparta pull request #36
Opened 2019-05-20 07:51 UTC by dannylwe

#### What does this PR do?
Enables users to like or dislike an article

#### Description of Task to be completed?
Users are able to offer sentiment to an article by liking or disliking the article

#### How should this be manually tested?
run `git fetch `
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-05-20 10:03 UTC, ezrogha submitted a review, later dismissed
Good work @dannylwe,
Kindly work on this feedback

2019-05-20 10:03 UTC, ezrogha commented on .netlify/state.json
> +}
What is the purpose of this file @dannylwe ?

2019-05-20 10:03 UTC, ezrogha commented on src/actions/likeDislikeActions.js
> +    console.log(response.data);
Please don't forget to remove these console logs when your PR is ready

2019-05-20 10:03 UTC, ezrogha commented on src/actions/profileActions.js
> +/* eslint-disable no-restricted-globals */
Please remove this comment

2019-05-20 10:03 UTC, ezrogha commented on src/components/Articles/ArticleDetail.jsx
> +                  height="70px"
kindly push these attributes (width and height) to the css file

2019-05-20 10:03 UTC, ezrogha commented on src/components/Articles/ArticleDetail.jsx
> +            {/* this is where to put thumbs up/down */}
please remove this comment

2019-05-20 10:03 UTC, ezrogha commented on src/components/Articles/DisplayArticles.jsx
> +          style={{ boxShadow: '5px 10px 18px #888888' }}
Move styles to the css file

2019-05-20 10:03 UTC, ezrogha commented on src/components/Articles/article.scss
>      padding-top: 240px;
Use rem instead of px

2019-05-20 10:27 UTC, dannylwe commented on src/components/Articles/ArticleDetail.jsx
> +                  height="70px"
@ezrogha not my work, reformatting

2019-05-20 10:27 UTC, dannylwe commented on src/components/Articles/DisplayArticles.jsx
> +          style={{ boxShadow: '5px 10px 18px #888888' }}
@ezrogha not my work, reformatting

2019-05-20 10:27 UTC, dannylwe commented on src/components/Articles/article.scss
>      padding-top: 240px;
@ezrogha not my work, reformatting

2019-05-20 10:44 UTC, felixkiryowa requested changes

2019-05-20 10:44 UTC, felixkiryowa commented on .netlify/state.json
> +}
@dannylwe , you  should add a new line here

2019-05-20 12:15 UTC, dannylwe commented on src/actions/profileActions.js
> +/* eslint-disable no-restricted-globals */
@ezrogha necessary to remove eslint error. The rule is off in eslint but the error is persisting.

2019-05-21 17:08 UTC, dannylwe commented on .netlify/state.json
> +}
@felixkiryowa deleted file, not needed

2019-05-21 17:08 UTC, dannylwe commented on src/actions/likeDislikeActions.js
> +    console.log(response.data);
@ezrogha worked on feedback

2019-05-21 18:24 UTC, felixkiryowa submitted a review, later dismissed
@dannylwe Rename your branch to follow convention

2019-05-21 18:28 UTC, dannylwe commented
I noticed just now. Will have to close this PR and open a new one.

2019-05-22 14:08 UTC, dorothyas approved these changes
@dannylwe good work

2019-05-22 14:19 UTC, hadijahkyampeire approved these changes

2019-05-22 14:19 UTC, merged