#165675656 Hosting Application on Heroku
andela/ah-frontend-sparta pull request #5
Opened 2019-04-30 09:54 UTC by felixkiryowa

#### What does this PR do?

-  Hosting Application on heroku

#### Description of Task to be completed?
-  The app should be hosted on heroku such that it can be accessed from any where in the world

#### How should this be manually tested?
  pending

#### What are the relevant pivotal tracker stories?
[ #165675656](https://www.pivotaltracker.com/story/show/165675656)

#### Screen shots

<img width="1437" alt="Screenshot 2019-04-29 at 15 15 59" src="https://user-images.githubusercontent.com/28748289/56895457-da7df200-6a91-11e9-85f0-fc52b7b0a8c9.png">

-  Application hosting on heroku such that it can be accessesd from anywhere

[Finishes #165675656]

2019-04-30 11:13 UTC, dannylwe approved these changes
LGTM

2019-04-30 11:51 UTC, adesege commented
Did you also configure review apps and enabled pipeline development on Heroku? Pls share a screenshot of the pipeline page on Heroku

2019-04-30 13:36 UTC, dorothyas approved these changes

2019-04-30 13:53 UTC, ezrogha approved these changes
LGTM

2019-05-02 08:55 UTC, adesege commented
From the screenshot, it says you should connect to Github to enable review apps. Can you confirm if you have enabled this feature?

2019-05-02 12:04 UTC, adesege commented
Please rebase with develop

2019-05-02 13:06 UTC, adesege requested changes
You have not created a pipeline to create a deployment on the master branch. Please check the board for the acceptance criteria.

2019-05-03 09:43 UTC, felixkiryowa commented
> You have not created a pipeline to create a deployment on the master branch. Please check the board for the acceptance criteria.

I worked  on this feedback

2019-05-06 07:38 UTC, adesege requested changes

2019-05-06 07:38 UTC, adesege commented on Procfile
> +web: node server.js
Change this to `web: npm start` instead

2019-05-06 07:56 UTC, felixkiryowa commented on Procfile
> +web: node server.js
I have worked on the feedback

2019-05-06 08:11 UTC, adesege commented
You have merge conflicts. @felixkiryowa

2019-05-06 08:17 UTC, adesege approved these changes

2019-05-06 08:18 UTC, merged