#164798160    Setting up Sass css
andela/ah-frontend-sparta pull request #7
Opened 2019-04-30 16:23 UTC by felixkiryowa

#### What does this PR do?

-  Setting up  Sass 

#### Description of Task to be completed?
-  Setting up Sass to be used to write CSS for elements in the application

#### How should this be manually tested?

- Fetch this branch `git fetch origin ch-setup-sass-164798160`
- Checkout to the branch `git checkout ch-setup-sass-164798160`
- Run `npm install`
- Open `style.scss file in the scss folder at the root of the project.
- Write scss styles to HTML elements in that file.
- Run `npm run scss` command to compile sccs to css stored in the style.css file in the assets folder at the root of the project.
- Run `npm start`
#### What are the relevant pivotal tracker stories?
[#164798160](https://www.pivotaltracker.com/story/show/164798160)

#### Screen shots
<img width="1437" alt="Screenshot 2019-04-30 at 19 22 15" src="https://user-images.githubusercontent.com/28748289/56977201-52751680-6b7d-11e9-99ee-203a1150931b.png">

2019-04-30 17:38 UTC, dannylwe requested changes

2019-04-30 17:38 UTC, dannylwe commented on src/index.js
> +
@felixkiryowa this line is not necessary. Kindly revert

2019-04-30 17:38 UTC, dannylwe commented on scss/style.scss
> +}
Insert a final newline here and in the rest of the files. You can also enable this option in VSCode by adding "files.insertFinalNewline": true to your settings.json file

2019-04-30 17:38 UTC, dannylwe commented on public/dest/style.css
> +  color: #333; }
@felixkiryowa kindly move the curly bracket to a new line

2019-04-30 17:38 UTC, dannylwe commented on assets/css/style.css
> +  color: red; }
@felixkiryowa kindly move the curly bracket to a new line

2019-05-02 08:59 UTC, adesege requested changes

2019-05-02 08:59 UTC, adesege commented on package.json
> +    "scss": "node-sass scss/style.scss assets/css/style.css --watch"
You should configure webpack to handle this for you instead of running a script manually

2019-05-02 08:59 UTC, adesege commented on public/dest/style.css
> +  color: #333; }
You should not commit this file.

2019-05-02 11:35 UTC, adesege requested changes

2019-05-02 11:35 UTC, adesege commented on assets/css/style.css
> +h1 {
Remove this file pls

2019-05-02 11:35 UTC, adesege commented on jest.config.js
> +    '\\.(css|scss|jpg|png)$': '<rootDir>/ignore-css.js',
You can use `ignore-module.js` instead since the file handles image files as well

2019-05-06 07:41 UTC, adesege approved these changes

2019-05-06 07:43 UTC, merged